name: Crear APK
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Preparar proyecto
        run: |
          mkdir www
          cp index.html www/index.html
          npm init -y
          npm i @capacitor/core@7 @capacitor/cli@7 @capacitor/android@7 @aparajita/capacitor-biometric-auth@9
          npx cap init "Mis ahorros" com.misahorros.app --web-dir www
          npx cap add android
          npx cap sync
      - name: Compilar APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Mis-ahorros-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
